# https://travis-ci.org/ryanss/bdateutil

language: python

python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - pypy

install:
    - python setup.py install
    - pip install flake8
    - pip install coveralls

before_script:
    - flake8 bdateutil/*.py tests.py --ignore=F401,E402,F403,F405

script:
    - coverage run --omit=*site-packages*,*pypy* tests.py

after_success:
    - coveralls
