# https://travis-ci.org/ryanss/python-bdateutil

language: python

python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - pypy

install:
    - python setup.py install
    - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install flake8==2.6.2; fi
    - if [[ $TRAVIS_PYTHON_VERSION != 2.6 ]]; then pip install flake8; fi
    - pip install coveralls

before_script:
    - flake8 bdateutil/*.py tests/bdateutil_tests.py --ignore=F401,E402,F403,F405

script:
    - coverage run --omit=*site-packages*,*pypy*,*dateutil_tests* -m unittest discover tests/

after_success:
    - coveralls
